version: '3.8'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - remix
      - strapi
    networks:
      - webnet

  remix:
    build:
      context: ./remix
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=${NODE_ENV}
      - STRAPI_URL=${STRAPI_URL}
    expose:
      - "3000"
    depends_on:
      - strapi
    networks:
      - webnet

  strapi:
    build:
      context: ./strapi
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=${NODE_ENV}
      - DATABASE_CLIENT=${DATABASE_CLIENT}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_SSL=${DATABASE_SSL}
    expose:
      - "1337"
    depends_on:
      - postgres
    networks:
      - webnet

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - webnet

volumes:
  postgres_data:

networks:
  webnet:
